Update 1.6.2
theforeman/jenkins-job-builder pull request #2
Opened 2017-09-01 16:50 UTC by ehelms

2017-09-01 16:50 UTC, ehelms commented
This rebases onto 1.6.2 which is latest 1.x stable.

2017-09-01 17:00 UTC, ehelms commented
This will need to be push directly to local eventually. The testing strategy is:

 1) git clone and have this branch
 2) pip install . --upgrade
 3) git clone foreman-infra
 4) cd puppet/modules/jenkins_job_builder/files/theforeman.org
 5) ./generate_jobs

We should try to figure out getting these three commits into JJB properly though. As requiring to have this fork installed can be annoying.

2017-09-01 19:36 UTC, mmoll commented
rebase/merge needed?

2017-09-01 21:27 UTC, ekohl requested changes
The last patch (cancel-builds-on-update) was merged upstream: https://github.com/openstack-infra/jenkins-job-builder/commit/eb8a54fa45aa1f20aac1207972c0159bf3b09c1a

That means for 2.0 it won't be needed to include it and we only need to send the schedule-failed-builds plugin patch upstream. @GregSutcliffe since you're the author, mind doing the honors?

2017-09-01 21:27 UTC, ekohl commented on jenkins_jobs/modules/publishers.py
> +    if 'only-successful' in data:
Current master has ```only-if-success```: https://github.com/openstack-infra/jenkins-job-builder/blob/f2b01f7c5ca29f6cf3fa1040106ed9d81fad32af/jenkins_jobs/modules/publishers.py#L136

Actually the block above it does that too so I prefer to rewrite our jobs and not include this patch.

2017-09-06 11:14 UTC, GregSutcliffe commented
I can try to get that upstream, sure. Added to my todo, still a bit under 100% today ...

2018-02-26 09:03 UTC, evgeni commented
#3 rebases ontop of 2.0.2, so we should continue there?

2018-02-27 08:22 UTC, evgeni commented
we're not using our forked jjb anymore: https://github.com/theforeman/foreman-infra/pull/492

close? :)

2018-02-27 10:30 UTC, ekohl commented
Yep, much easier to just deprecate the entire repo :)

2018-02-27 10:30 UTC, closed without merging

2018-02-27 10:38 UTC, mmoll commented
could anybody set this repo to "archived" then? :)